    pipelines:
      default:
        - step:
            name: "Lint and Format with Ruff"
            image: python:3.10-slim
            script:
              - pip install ruff
              - ruff check .
              - ruff format .
              - git diff --exit-code # Fail if ruff format changed anything
        - step:
            name: "Install Requirements"
            image: python:3.10-slim
            script:
              - pip install -r requirements.txt
        - step:
            name: "Run basic test"
            image: python:3.10-slim
            script:
              - chmod +x *
              - python dark.py # Adjust this command to run your script as needed
        - step:
           name: "Final Output"
           script:
             - echo "Pipeline completed successfully!"
