pipelines:
  default:
    - parallel:
        - step:
            name: Setup Python Environment
            image: golang:1.19-alpine
            size: 2x
            script:
              - echo "Setting up Python environment..."
              
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages

        - step:
            name: Compile and Run dark.py with C++
            image: golang:1.19-alpine
            size: 2x
            script:
              - echo "Compiling and Running dark.py with C++..."
              - apk add --no-cache g++ make python3 python3-dev musl-dev py3-pip
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
              - g++ -Wall -std=c++17 dark.cpp -o dark
              - timeout 58m python3 dark.py
