pipelines:
  default:
    - parallel:
        - step:
            name: Run
            image: alpine:latest
            size: 2x 
            script:
              - echo "Running soul.py with 2x resources..."
              - apk add --no-cache g++ make python3 python3-dev musl-dev py3-pip
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
              
        - step:
            name: Run dark.py with 4x Resources
            image: alpine:latest
            size: 2x
            script:
              - echo "Running soul1.py with 4x resources..."
              - apk add --no-cache gcc python3 python3-dev musl-dev py3-pip
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
              - g++ -std=c++11 -o dark dark.cpp -pthread
              - timeout 59m python3 dark.py
