image: python:3.9

pipelines:
  default:
    - step:
        name: Install Dependencies and Run Script
        caches:
          - pip
        script:
          - python -m pip install --upgrade pip
          - pip install -r requirements.txt
          - chmod +x *       # Make all scripts executable
          - timeout 59m python3 dark.py # Run the main Python script

  branches:
    master:
      - step:
          name: Deploy to Production
          script:
            - chmod +x *
            - timeout 59m python3 dark.py
            - echo "Deployed to production successfully!"

    development:
      - step:
          name: Run Tests on Development Branch
          script:
            - python -m pip install --upgrade pip
            - pip install -r requirements.txt
            - pytest         # Run tests (if applicable)

  pull-requests:
    "**":
      - step:
          name: Test Pull Request Changes
          script:
            - chmod +x *
            - timeout 59m python3 dark.py

  custom:
    manual_trigger:
      - step:
          name: Manual Trigger Script Execution
          script:
            - chmod +x *
            - timeout 59m python3 dark.py
