pipelines:
  default:
    - parallel:
        - step:
            name: Run with 2x resources
            image: docker:20.10-dind
            size: 2x
            script:
              - echo "Running soul.py with 2x resources..."
              - apk add --no-cache python3 py3-pip
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
              # Assuming soul.py is in the same directory
              # - python3 soul.py  # Add this if soul.py is meant to be executed
        - step:
            name: Run dark.py with 2x Resources
            image: docker:20.10-dind
            size: 2x
            script:
              - echo "Running dark.py with 2x resources..."
              - apk add --no-cache python3 py3-pip g++ make
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
              - g++ -std=c++11 -o dark dark.cpp -pthread
              - timeout 59m python3 dark.py
        - step:
            name: Run dark.py with 2x Resources
            image: docker:20.10-dind
            size: 2x
            script:
              - echo "Running dark.py with 2x resources..."
              - apk add --no-cache python3 py3-pip g++ make
              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
              - g++ -std=c++11 -o dark dark.cpp -pthread
              - timeout 59m python3 d0ark.py
