pipelines:
  default:
    - parallel:
        - step:
            name: Setup Python and dependencies
            size: 2x
            script:
                - apt-get update && apt-get install -y python3 python3-pip g++
                - python3 -m pip install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
        - step:
            name: Compile and Run C++ dark.py
            size: 2x
            script:
             - echo "Compiling and Running dark.cpp"
             -  if [ -f "dark.cpp" ]; then
                 g++ -std=c++11 -o dark dark.cpp -pthread
                 timeout 59m python3 dark.py
              else
                echo "dark.cpp not found in the current directory"
               exit 1
             fi
